# Syllabus: PMAP (4041), Fall 2024: Econometrics for Policy Analysis
::: {.callout-note}
This is an ongoing project. Comments and suggestions are welcome.
[Jared Greathouse](https://jgreathouse9.github.io/). Office Hours: By Request.
:::

Every day, governments pass laws/public policy to affect some
outcome of interest. Policy usually touches thousands if not *millions* of people. From traffic-circles to pop/sugar sweetened beverge taxes, vaccine mandates and universal pre-k programs, cannabis legalization
to minimum wages, public policy impacts us all from birth to death.

Policy is never self justifying. It demands evaluation. If California bans tobacco smoking in public,
or if New York City implements gun control, presumably we would agree these *likely*
impact outcomes like tobacco use or homicide rates, ideally decreasing both of them.


```{python}
#| echo: false
#| code-fold: true
#| fig-align: center
#| engine: jupyter

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib


# Matplotlib theme
Jared_theme = {
    "axes.grid": True,
    "grid.linestyle": "-",
    "legend.framealpha": 1,
    "legend.facecolor": "white",
    "legend.shadow": True,
    "axes.facecolor": "white",
    "grid.color": "#D3D3D3"
}
matplotlib.rcParams.update(Jared_theme)

link = r"https://raw.githubusercontent.com/synth-inference/synthdid/master/data/california_prop99.csv"

df = pd.read_csv(link, sep=';')

# Assuming 'Year' is the name of the column you want to sort by
Cali = df[df['State'] == 'California'] .reset_index() # Filter rows where the first column is 'California'
Cali = Cali.sort_values(by='Year')

# Create a NumPy array for PacksPerCapita
packs_per_capita = Cali['PacksPerCapita'].to_numpy()

treatyear = Cali[Cali['treated'] == 1].index.min()+1970

# Create a range of values from 1970 to 2000 for the x-axis
years_range = np.arange(1970, 2001)
# Adding a vertical line at treatyear
plt.axvline(x=treatyear, color='grey',
linestyle='--',
label='Proposition 99',
linewidth=1.5)


# Plotting PacksPerCapita versus Year
plt.plot(years_range, packs_per_capita, 
linestyle='-', 
color='black', 
label='California', linewidth=2)



# Adding labels and title
plt.xlabel('Year')
plt.ylabel('Cigarette Sales Per Capita')
plt.title('An Anti-Tobacco Policy: Proposition 99')
plt.legend()
plt.show()
```


If California's anti-tobacco policy didn't affect smoking rates at all (or worse, if more people began to smoke) or if gun control has 0 impact on homicide rates (or increased them, paradoxically), then surely these could not be justified in the very first place.
Before we continue, understand fundamentally these outcomes being affected *are* the point. The only reason that we, as a society,
do policy is precisely **because** we think policy affects (or should affect) people somehow.
If political science studies "who gets what where", one summation of policy studies
might be "what works?" But what policies should we care about? How can we know if they work?
This is the starting point for empirical policy analysis. This class discusses the theory and process for how statistical analysis of data may be used to answer policy questions.

## Course Philosophy and Structure

I believe the best way to demonstrate knowledge of policy analysis is through *writing*. As such, there will be no quizzes or in-class exams. Why? It is unrealistic. In real life, rarely do we have an hour and 30 minutes or a ten minute quiz window on the internet to write a full summation of our ideas or think through a question. Typically, we have much more time and resources to help us. In fact, proper use of resources is what makes a good analyst: good analysts don't need to remember everything, but they do need to be good at *finding answers* and using them sensibly. In this spirit, your sole assignment is to write a paper *applying* the statistical concepts/ideas we cover here to answer questions about a real policy. Here is the breakdown of your grade.

- 35% of your grade comes from the first draft 15% question and 20% draft.
- 60% for the final paper and presentation (respectively, 30 percent each), and
- 5% for attendence.

You must find a real policy that exists which you expect to affect an outcome. You will discuss the justification for the policy (including why we should care about its effects). You'll gather data on the policy of interest. Finally, you'll use the statistical tools we cover (probability theory, descriptive statistics, and regression) to discuss its effects. Typically, we ask causal questions where only one intervention is of interest, but associative papers are not ruled out inherently.

In many senses, public policy is a catch all term covering various disciplines. Public health scholars may care about how banning of abortion in Texas affected fertility rates, or how COVID-19 vaccine/mask mandates affected the COVID-19 case rate per capita compared to other jurisdictions that did not enact these policies. Criminologists may care about how the building of Cop City affected how many people are shot by police, or how a state legalizing cannabis affects crime rates or the consumption of alcohol. Policy historians may care about how Pinochet's 1973 economic policies affected the GDP of Chile or about how Britain's National Health Service of 1948 affected infant mortality. Environmental scholars may ask how Hurricane Katrina affected the economy of New Orleans. These are just some fields; increasingly, empirical methods of analysis are used in the business sector as well as other fields. Given the array of areas and topics, I don't care about what policy you choose. You may study whatever is is 1) quantifiable with **accessible** data and 2) interesting to you. To quote Noam Chomsky (who was quoting another MIT professor), the important part isn't what we cover in class; it is about what we discover.

## Helpful Notes from Me

1. Sun Tzu [said](https://suntzusaid.com/book/1) every battle is won before it is fought. To reverse the perspective, as Ben Franklin said, if you fail to prepare, prepare to fail.
2. Please, do contact me if you have questions. Policy data analysis is what I do in my research every day. I love what I do, and I love discussing this topic with others. If you have any questions about the ideas we cover in class or have any difficulties, you may always meet with me or contact me otherwise.
3. Main Takeaways: In addition to statistics, the main goal of the course is to provide the reasoning skills scientists use to understand the world better. These skills will be useful not just in academia or even the professional workforce, but every day life.


## Additional Requirements
1. If I feel the concept is important, it'll be in the lecture notes or we will discuss it. I will also assign external readings to be done before class.

2. There is no required textbook (aside from this one!) for this course. Various free textbooks exist such as [Introductory Econometrics with R](https://www.econometrics-with-r.org/), [Introductory Statistics](https://saylordotorg.github.io/text_introductory-statistics/), [Intro to Modern Statistics](https://openintro-ims.netlify.app/), [Regression and Other Stories](https://users.aalto.fi/~ave/ROS.pdf), [INtro to Econometrics](https://kaplandm.github.io/Kaplan_Intro_Econometrics_text.pdf), [Intro to Political Science Research Methods](https://asccc-oeri.org/wp-content/uploads/2020/06/IntroPS_Methods_PDF.pdf), and [many](https://rafalab.dfci.harvard.edu/dsbook-part-2/) [others](https://bookdown.org/lgpcappiello/introstats/). The Policy Department at Georgia State also recommends [Introduction to Research Methods](https://bookdown.org/ejvanholm/Textbook/) or [Research Methods for the Social Sciences](https://courses.lumenlearning.com/suny-hccc-research-methods/). I will recommend chapters from each book to read (of course, you need only read one chapter, from either text). The corresponding lecture will focus on the content that each respective chapter covers. Note that these books cover different aspects of the course in different levels of depth (Gelman's book *Regression and Other Stories* is obviously mainly about regression, one of the last topics we cover, whereas the others are more rudimentary).

3. The same is true for software-- I don't care which of these you use, but the only ones I know well are Stata, Python, and R. For Stata users, [Statalist](https://www.statalist.org/forums/) is a great resource for Stata. R also is backed by a vast statistician community.

# To Do

1. Precise Scheduling (e.g, chapters to read, dates, etc under development)


